#!python3
from parts import *

#enable smart linking
SetOptionDefault("LINKFLAGS", ['-Wl,--copy-dt-needed-entries', '-Wl,--as-needed'])
SetOptionDefault("CXXFLAGS", ['-std=c++17', '-fPIC'])
SetOptionDefault("INSTALL_ROOT", "#")

# control shim for trafficserver
AddOption("--with-trafficserver",
          dest='with_trafficserver',
          nargs=1,
          type='string',
          action='store',
          metavar='DIR',
          default=None,
          help='Optional path to custom build of trafficserver')

AddOption("--with-ssl",
          dest='with_ssl',
          nargs=1,
          type='string',
          action='store',
          metavar='DIR',
          default=None,
          help='Optional path to custom build of OpenSSL'
         )


# the depends
Part("swoc++/swoc++.part"
        ,vcs_type=VcsGit(server="github.com", repository="SolidWallOfCode/libswoc", tag="1.1.0")
        )
Part("#lib/libyaml-cpp.part", vcs_type=VcsGit(server="github.com", repository="jbeder/yaml-cpp.git", protocol="https", tag="yaml-cpp-0.6.3"))

# this is just a shim part. it passes info based on stuff being installed on the box
# it should have a better check for the real version of trafficserver being used
ts_path = GetOption("with_trafficserver")
Part("#lib/trafficserver.part", PKG_PREFIX=ts_path, PKG_VERSION="10.0.0")

path = GetOption("with_ssl")
Part("#lib/openssl.part", CUSTOM_PATH=path)
Part("#lib/libyaml-cpp.part")

# The main build.
Part("plugin/txn_box.part", package_group='txn_box')
Part("test/unit_tests/unit_tests.part")
